### ISSUE TITLE
Auto picking 2nd level reviewer

### ISSUE THREAD

**Issue by harsha-bhat-coupa** [aergonaut/cody#29]
It would be cool to add 2nd level reviewer automatically based on the [load](https://coupa-pickaxe.herokuapp.com/search/reviewers) each one have and the modules they are related to (though 2nd part doesnt matter much).

**Comment by aergonaut** [comment]
This is already possible through use of the new review rules system. With rules we would choose a random reviewer from the list, which should statistically ensure even load among all members of the list.
