### ISSUE TITLE
Bug in refresh_config

### ISSUE THREAD

**Issue by aergonaut** [aergonaut/cody#332]
When refreshing config from the config file, we use `find_or_initialize_by` with all of the rule's attributes. This means that the attributes actually can't be updated in the file.

https://github.com/aergonaut/cody/blob/master/app/models/repository.rb#L105

**Comment by recepaslan** [comment]
Same applies for diff ?
https://github.com/aergonaut/cody/blob/c3dd01baa80068721ed6b6a6776f609e630227d2/app/models/repository.rb#L111
