### ISSUE TITLE
Approving messages left in a github review do not approve

### ISSUE THREAD

**Issue by IanMcNelly** [aergonaut/cody#336]
When a reviewer uses the Github Review feature and leaves their approval message in the approving review, cody does not detect this and a second approval comment is needed. If the reviewer is in a different timezone than the requester and doesn't notice, this can delay a PR by a few days. Heres some examples:
![image](https://user-images.githubusercontent.com/7926806/54827763-1ea6f700-4c89-11e9-9e1e-9c4a275ba4a7.png)
![image](https://user-images.githubusercontent.com/7926806/54827793-2e264000-4c89-11e9-9438-3de913933790.png)
![image](https://user-images.githubusercontent.com/7926806/54827819-3aaa9880-4c89-11e9-8623-084e253f72e4.png)

**Comment by aergonaut** [comment]
Implemented in #389. Reviewers just need to leave an approving review through the GitHub interface. No need for any special text inside the review comment, as long as the review is an approval.
