### ISSUE TITLE
Reviewers must be unique

### ISSUE THREAD

**Issue by aergonaut** [aergonaut/cody#4]
It's currently possible to list the same reviewer n times in the reviewers list and have that reviewer be counted n times. Any one reviewer should only be counted once in the reviewers list.

We should either silently filter out the duplicates or raise a new error.

**Comment by robertmonahon** [comment]
Again here I'd favor a silent error and let duplicates slide as long as we have enough.  I assume we'd end up in a state where we have checks for reviewers.unique.size >= 2 and super_reviewers.unique.size >=1 with 1 and 2 being potentially dynamic if we start enforcing risk level labels.
