### ISSUE TITLE
RFC: Redesign PR delegation feature

### ISSUE THREAD

**Issue by aergonaut** [aergonaut/cody#405]
The current implementation of the PR delegation feature is very light and has no restrictions on what two PRs can be linked together. This is potentially problematic if delegation is misused to link unrelated PRs, or to link PRs with diffs that are different. We would like to redesign the feature so that it could be used for its original intent while preventing misuse.

---

A first proposal is to restrict delegation to PRs that have identical diffs. When creating the link, we would compare the full diff of the two PRs together, and if they are the same, then the link would be made; if they are different, the link would not be made, and reviewers would be assigned as normal.

Another question related to this is how to indicate to users that the link did not work and, more importantly, why it did not work. The simplest action would be to comment as Cody's bot user.

---

Proposals:

1. Only assign reviewers from certain Review Rules when a PR is delegated. @fqureshi @pravin-coupa
2. Use the link to assign the same reviewers to the new PR instead of directly linking the code review status. @alcima-coupa @rebeccamengell
3. Allow direct linking of code review status but only if the diffs of the two PRs are identical. @rebeccamengell @recepaslan
4. Only allow PRs with certain base branches to use delegation. @recepaslan

**Comment by fqureshi** [comment]
Just another proposal: If we decide we absolutely need some kind of review for delegated PR's, maybe we should only assign a Second Level Reviewer and leave it at that? Second Level Reviewers would understand what is appropriate for a maintenance release.

**Comment by alcima-coupa** [comment]
My quick thoughts were - 1) Only allow the link to be from an unreviewed master PR to a reviewed 0nn_release identical PR  2) Only use the link to force the same reviewers onto the linked PR

**Comment by rebeccamengell** [comment]
Would the diff approach solve the problem? If I cherry-pick my migration from master, seems it still might not be appropriate for an earlier release. Same is probably true for some validation and integration changes. Could we pair them, so the same reviewers are assigned? If we could flag them as the identical or different, its at least a clue what we should be looking for.

**Comment by recepaslan** [comment]
Agree on @aergonaut suggestion on identical diffs. Otherwise, code should always be reviewed. We need to consider also rebasing. What will happen if reviews are identical but later changes are introduced due to rebasing? 

In addition to this approach, it is also better to check the direction of the delegation. If the maintenance branch pull request delegated from a pull request for master, it is likely to fail and have this issue again. 

One small another point on the naming, different repository that shares Cody, has different maintenance branch renaming.

**Comment by aergonaut** [comment]
We could make it so that only PRs whose base branch is the repo's default branch are allowed to use delegation. That would solve any naming convention problems, and also generally match with the idea of allowing "backwards" delegation but blocking "forwards" delegation.

**Comment by recepaslan** [comment]
> We could make it so that only PRs whose base branch is the repo's default branch are allowed to use delegation. That would solve any naming convention problems, and also generally match with the idea of allowing "backwards" delegation but blocking "forwards" delegation.

One better way to do it

**Comment by pravin-coupa** [comment]
A thought for quick implementation:
We can may be allow both forward or backward delegations BUT add new reviewers section only for delegated PRs; something like "**Delegated PR reviewer**" (e.g. like API, Migration, second_level) and have only set of reviewers to approve this.

**Comment by aergonaut** [comment]
Updated main comment to summarize current proposals

**Comment by aergonaut** [comment]
**Motion to close** 

I motion to close this RFC and accept the "forward delegation" solution, originally proposed by @recepaslan in [this comment](https://github.com/aergonaut/cody/issues/405#issuecomment-591710094).

Cody will add a new configuration parameter `loose_delegation` that will allow the old behavior of unrestricted delegation to apply.

The new default delegation behavior will be called "Strict Delegation" and will require that for a PR to delegate it's code review, it's base branch must equal the repository's default branch.

Assume there are PRs 🅰️ and 🅱️. Assume the repository's default branch is named ♠️; there also exists another branch in the repository named ♥️ that PRs also get merged into.

Given:

| | 🅰️ | 🅱️ |
| - | - | - |
| base | ♠️ | ♥️ |

Therefore:

| | 🅰️ `Reviewed in 🅱️` | 🅱️ `Reviewed in 🅰️` |
|-|-|-|
| Allowed? | 🙆‍♀️ | 🙅‍♀️ |

🅰️ can delegate to 🅱️ (by writing `Reviewed in 🅱️` in 🅰️'s description) because 🅰️'s base branch is ♠️, which is the same as the repository's default branch.

🅱️ cannot delegate to 🅰️ because 🅱️'s base branch is ♥️ (in our terms, 🅱️ is "targeted" for ♥️).
