### ISSUE TITLE
Cody still assigns Second level reviewer despite "Reviewed in..."

### ISSUE THREAD

**Issue by dwebiorn-coupa** [aergonaut/cody#412]
**Describe the bug**
When I wrote "Reviewed in...", cody still assigned Second Level Reviewer.

**To Reproduce**
1. Go to create a PR
2. In reviewers, fill in "Reviewed in..."
3. Create PR
4. Cody will still set Second Level Review label and assign Second Level Reviewer

**Expected behavior**
No reviewers will be assigned to the pr

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: OS X Catalina
 - Browser: Chrome
 - Version Version 81.0.4044.92 (Official Build) (64-bit)

**Comment by ranand** [comment]
possibly related to https://github.com/aergonaut/cody/issues/405 and I think it was removed a while back.

**Comment by aergonaut** [comment]
Yep, @ranand is correct. This is intentional. See #405.
