### ISSUE TITLE
Evolution to use requested reviews

### ISSUE THREAD

**Issue by aergonaut** [aergonaut/cody#59]
The Review Requests API is now in public beta so we should start using it: https://developer.github.com/v3/pulls/review_requests/

This will probably lead to a significant reworking on how Cody tracks reviews, how Cody reports the status of the review, how contributors indicate who they want to review, etc., etc.

Here's a wall of text representing my thoughts:

---

### Current behavior

Contributors request a review by listing reviewers using a GitHub Task List in the PR body.

### New behavior

Contributors request review using the Request Review feature in the GitHub UI.

### Pros

* More filtered autocomplete for which users can be chosen. Technically anyone can be mentioned in a PR body even if they don't have access to the repo that owns the PR. But you can only request a review from someone with collaborator access to the repo.
* Audit trail for review assignments. It will be more clear who added a reviewer to the list, if a reviewer was removed or swapped, etc.

### Cons

* Harder to replicate review lists across PRs. Currently you can just copy the PR body, now you would have to reselect the reviewers in each PR.
* Can't have pre-approved reviews.

### Current behavior

Cody maintains its own list of pending and completed reviews. It uses webhooks to detect when a reviewer approves and synchronizes the state.

### New behavior

Cody will no longer track review state as review state is now a first-class attribute of the PR.

### Pros

* No loss of synchronization. Cody can sometimes get out of synch if a reviewer forgets to comment or if the review list changes and no one updates Cody.
* Less data to track.

### Cons

* None?

### Current behavior

Cody reports the status of the review on the PR in the namespace **code-review/cody**.

### New behavior

Cody will no longer report code review status on the PR. Review status is a first-class attribute and surfaces up on the PR already.

### Pros

* Less data to track. We no longer have to move status indicators forward when a new commit is pushed or a PR is rebased.

### Cons

* It's more convenient if the code review status shows up as commit status because the commit statuses roll up into a single status on the PR. It's convenient to surface the code review status here.

### Current behavior

Cody adds generated reviewers in separate Task Lists at the bottom of the PR body.

### New behavior

Cody will create review requests for generated reviewers and add them to the PR.

### Pros

* No more accidental or unintentional copying of generated reviewers from one PR to another if the author wants to copy the body of the PR over.
* Generated reviewers will show up in the same place as regular reviewers so it's harder for them to be overlooked.

### Cons

* Still can't tell if we've already run review rules against a PR or not.

**Comment by edk** [comment]
the only 😞 I see so far is the Cons for requesting a review

* Harder to replicate review lists across PRs. Currently you can just copy the PR body, now you would have to reselect the reviewers in each PR.
* Can't have pre-approved reviews.

the rest of this sounds good to me though! 👍

**Comment by zrandles** [comment]
I agree with Eddy. Preserving the ability to replicate review lists/skip approvals on propagations would be nice. Could you:

Create a reviewer (rather than an assignee) when - [ ] @zrandles is added
Not create a reviewer when - [x] @zrandles is added

**Comment by robertmonahon** [comment]
Requesting a Review - Agree with above.  Nothing new to add.

Tracking Review State - Looks good.  Agree no real cons here.

Review Status Indication - I really like that today Cody reviews carry same weight as test failures in our minds.  Red PR = no merge, and I'd be sad to lose that.  I don't know what the UI would look like, but changing this would probably require an update to our other merge tools if reviews were no longer exactly like a failing test.

Generated Reviewers - I took a quick look at the documentation and I don't see any way to track a Type alongside the review, only a Status.  Cody could use reviewer group membership to assume which type of reviews are covered on the PR, but calling them out specifically gives a clearer directive to the reviewer on what they're looking at.

**Comment by aergonaut** [comment]
Maybe I can start adding a comment to the PR thread with instructions for reviewers. I don't like editing the body, so I want to avoid that.

**Comment by aergonaut** [comment]
> Review Status Indication - I really like that today Cody reviews carry same weight as test failures in our minds. Red PR = no merge, and I'd be sad to lose that. I don't know what the UI would look like, but changing this would probably require an update to our other merge tools if reviews were no longer exactly like a failing test.

I agree with this. I think this could still be done by having Cody listen to the webhook for Pull Request Review, so when a review is submitted, Cody can look at all the reviews and roll them up into a status to apply to the PR.

> Generated Reviewers - I took a quick look at the documentation and I don't see any way to track a Type alongside the review, only a Status. Cody could use reviewer group membership to assume which type of reviews are covered on the PR, but calling them out specifically gives a clearer directive to the reviewer on what they're looking at.

I agree with this too. I think if Cody starts making a comment on the PR with something like what currently gets added to the PR body, that would be almost the same.

---

Actually I guess this is as good a time as any to work out how to link one PR to another. Here's my idea:

Add a `parent_id` reference to `pull_requests` that points back to the parent PR. Child PRs delegate their review status to the parent.

```
+---------------+
| pull_requests |
+---------------+
| id            | <--+
| ...           |    |
| parent_id     | ---+
+---------------+
```

When you open a child PR, you use a special tag in the PR body to link the reviews. Some options for tags:

* `!link-reviews <PARENT>`: Consistent with Cody's current directive format
* `[cody:parent=<PARENT>]`: Maybe a little nicer to look at?
* Something else?

Cody marks the PR with a pending status and the message "Review delegated to <PARENT>". The Details link will point to the parent PR as well.

When the parent PR is approved, it copies its status onto all of the child PRs and updates them.

**Comment by zrandles** [comment]
I like having the entire comment of the child PR be:

Propagation of https://github.com/coupa/coupa_development/pull/37302

I think that's easier to remember than a special cody directive. Cody could look for a line that matches /prop.*(https:\/\/.github.com*)/i
