### ISSUE TITLE
Allow one PR to defer review status to another PR

### ISSUE THREAD

**Issue by mynameisdaniel** [aergonaut/cody#7]
A common workflow is a developer creates a propagation to the target branch which is code reviewed and then cherry picks those changes to a different branch which references the first branch. Only one pr gets reviewed unless there are substantial changes.

Cody throws an error unless we tag code reviewers for each PR. Cody should be able to either skip the check or be able to check the PR that is code reviewed.

**Comment by zrandles** [comment]
Just came here to create this. Rough idea of things to check:

- Is the first line of the description "CR: " followed by a link to a ticket?
- Does that ticket have the same JIRA number?
- Does that ticket meet all conditions to merge?

Note: if we do it this way, we need to make sure we can't get stuck in an infinite loop if two tickets refer to each other.

**Comment by aergonaut** [comment]
I don't want to get too sophisticated in this. I'd rather provide a simpler mechanism.

My idea for this was if the PR description contains /CR:\s+#(\d+)/ then we should link the two PRs and copy the referenc*ed* PR's status onto the referenc*ing* PR's status. The referencing PR's status should update whenever the referenced PR's status updates.

I don't think we should validate anything about ticket numbers or branches when establishing the reference. Sure that allows people to make bad references, but I don't think that should really be a problem. Validation code would probably be pretty complex anyway.

Cycle detection I also think we can probably leave out. That seems like a pretty difficult thing to get into by accident.

**Comment by zrandles** [comment]
Linking is a good idea, I like that approach.

Fair enough about cycle detection.

**Comment by aergonaut** [comment]
This has been implemented and will be in the next release announcement.
